-- PostgreSQL Schema for california_schools database

-- The 'schools' table is created first as other tables have foreign key references to it.
CREATE TABLE "schools" (
    "CDSCode" TEXT PRIMARY KEY,
    "NCESDist" TEXT,
    "NCESSchool" TEXT,
    "StatusType" TEXT NOT NULL,
    "County" TEXT NOT NULL,
    "District" TEXT NOT NULL,
    "School" TEXT,
    "Street" TEXT,
    "StreetAbr" TEXT,
    "City" TEXT,
    "Zip" TEXT,
    "State" TEXT,
    "MailStreet" TEXT,
    "MailStrAbr" TEXT,
    "MailCity" TEXT,
    "MailZip" TEXT,
    "MailState" TEXT,
    "Phone" TEXT,
    "Ext" TEXT,
    "Website" TEXT,
    "OpenDate" DATE,
    "ClosedDate" DATE,
    "Charter" BOOLEAN,
    "CharterNum" TEXT,
    "FundingType" TEXT,
    "DOC" TEXT NOT NULL,
    "DOCType" TEXT NOT NULL,
    "SOC" TEXT,
    "SOCType" TEXT,
    "EdOpsCode" TEXT,
    "EdOpsName" TEXT,
    "EILCode" TEXT,
    "EILName" TEXT,
    "GSoffered" TEXT,
    "GSserved" TEXT,
    "Virtual" TEXT,
    "Magnet" BOOLEAN,
    "Latitude" DOUBLE PRECISION,
    "Longitude" DOUBLE PRECISION,
    "AdmFName1" TEXT,
    "AdmLName1" TEXT,
    "AdmEmail1" TEXT,
    "AdmFName2" TEXT,
    "AdmLName2" TEXT,
    "AdmEmail2" TEXT,
    "AdmFName3" TEXT,
    "AdmLName3" TEXT,
    "AdmEmail3" TEXT,
    "LastUpdate" DATE NOT NULL
);

CREATE TABLE "frpm" (
    "CDSCode" TEXT PRIMARY KEY,
    "Academic Year" TEXT,
    "County Code" TEXT,
    "District Code" INTEGER,
    "School Code" TEXT,
    "County Name" TEXT,
    "District Name" TEXT,
    "School Name" TEXT,
    "District Type" TEXT,
    "School Type" TEXT,
    "Educational Option Type" TEXT,
    "NSLP Provision Status" TEXT,
    "Charter School (Y/N)" BOOLEAN,
    "Charter School Number" TEXT,
    "Charter Funding Type" TEXT,
    "IRC" BOOLEAN,
    "Low Grade" TEXT,
    "High Grade" TEXT,
    "Enrollment (K-12)" DOUBLE PRECISION,
    "Free Meal Count (K-12)" DOUBLE PRECISION,
    "Percent (%) Eligible Free (K-12)" DOUBLE PRECISION,
    "FRPM Count (K-12)" DOUBLE PRECISION,
    "Percent (%) Eligible FRPM (K-12)" DOUBLE PRECISION,
    "Enrollment (Ages 5-17)" DOUBLE PRECISION,
    "Free Meal Count (Ages 5-17)" DOUBLE PRECISION,
    "Percent (%) Eligible Free (Ages 5-17)" DOUBLE PRECISION,
    "FRPM Count (Ages 5-17)" DOUBLE PRECISION,
    "Percent (%) Eligible FRPM (Ages 5-17)" DOUBLE PRECISION,
    "2013-14 CALPADS Fall 1 Certification Status" BOOLEAN,
    FOREIGN KEY ("CDSCode") REFERENCES "schools" ("CDSCode")
);

CREATE TABLE "satscores" (
    "cds" TEXT PRIMARY KEY,
    "rtype" TEXT NOT NULL,
    "sname" TEXT,
    "dname" TEXT,
    "cname" TEXT,
    "enroll12" INTEGER NOT NULL,
    "NumTstTakr" INTEGER NOT NULL,
    "AvgScrRead" INTEGER,
    "AvgScrMath" INTEGER,
    "AvgScrWrite" INTEGER,
    "NumGE1500" INTEGER,
    FOREIGN KEY ("cds") REFERENCES "schools" ("CDSCode")
);